# -*- coding: utf-8 -*-
"""ExrciseNatLan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Ky4awyWRll4OK7qRlLfbf_0Ond7KYYs

# **Load the Book**
"""

with open("/content/miracle_in_the_andes.txt", "r") as file:
  book = file.read()

book

"""# **Extract the Paragraph were Love was used**"""

import re
pattern = re.compile("[^\n\n]*love[^\n\n]*")
love_word = re.findall(pattern, book)
love_word

"""# **Extract Chapters Titles**

"""

pattern = re.compile("Chapter [0-9]+[\n\n]*[^\n\n]*")
title_chapter = re.findall(pattern, book)
title_chapter

from typing import Dict
book


def word_count(x):
  pattern = re.compile("[a-zA-Z]+") #Give me everything except
  word_count = re.findall(pattern , book.lower())
  dict_word = {}
  for word in word_count:
    if word in dict_word.keys():
      dict_word[word] = dict_word[word]+1
    else:
      dict_word[word]= 1
  return dict_word[x]

word_count('love' )